name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: ./angular

    - name: Run tests
      run: npm test -- --browsers=ChromeHeadless --watch=false
      
      working-directory: ./angular
      continue-on-error: true # Остановить pipeline, если тесты не прошли

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag angular-starter:$(date +%s)

    #- name: Log in to GitHub Container Registry
      run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ angular-react-starter_Leto13 }} --password-stdin

    #- name: Build and tag Docker image
      run: docker build -t ghcr.io/${{ angular-react-starter_Leto13 }}/${{ angular-react-starter }}/angular-starter .

    #- name: Push Docker image to GitHub Packages
      run: docker push ghcr.io/${{ angular-react-starter_Leto13 }}/${{ angular-react-starter }}/angular-starter
      
    #- name: Send failure email
    #  if: failure()
    #  uses: dawidd6/action-send-mail@v4
    #  with:
    #    server_address: smtp.gmail.com
    #    server_port: 465
    #    username: ${{ ivan.tokovoy93 }}
    #    password: ${{ password }}
    #    subject: "Test Pipeline Failed"
    #    to: ${{ secrets.NOTIFY_EMAIL }}
    #    from: ${{ secrets.ivan.tokovoy93 }}
    #    body: "The test pipeline has failed. Please check the logs for more details."
